/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VersionBookChapterRouteImport } from './routes/$version.$book.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionBookChapterRoute = VersionBookChapterRouteImport.update({
  id: '/$version/$book/$chapter',
  path: '/$version/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$version/$book/$chapter': typeof VersionBookChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$version/$book/$chapter': typeof VersionBookChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$version/$book/$chapter': typeof VersionBookChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$version/$book/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$version/$book/$chapter'
  id: '__root__' | '/' | '/$version/$book/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VersionBookChapterRoute: typeof VersionBookChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$version/$book/$chapter': {
      id: '/$version/$book/$chapter'
      path: '/$version/$book/$chapter'
      fullPath: '/$version/$book/$chapter'
      preLoaderRoute: typeof VersionBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VersionBookChapterRoute: VersionBookChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
